config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'todos', to: 'todos#index', as: 'todos'
  get 'todo/:todo_id', to: 'todos#show', as: 'todo'
  patch 'todos/:todo_id', to: 'todos#update', as: 'update_todo'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tasks#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :todos
  has_many :users, through: :todos
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :load_tasks

  has_many :todos
  has_many :tasks, through: :todos


private

  def load_tasks
  Task.all.each do |task|
  Todo.create(
     task_id: task.id,
     user_id: self.id
    )

     end

   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index]
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index

   if user_signed_in?
   @todos = current_user.todos
   else
     @tasks = Task.all


  end
  end

  def show
  end

  def edit
  end

  def destroy
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
      @todos = Todo.all
      @tasks = Task.all
    end

    def show
      todo = Todo.find(params[:todo_id])
      @task = todo.task
      @todos = Todo.where(task_id: @task.id, completed: true)
    end

    def update
      todo = Todo.find(params[:todo_id])
      todo.completed = !todo.completed
      todo.save
      redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaNPrueba</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-light text-dark bg-warning">
      <a class="navbar-brand">
        <h5>Lista de tareas para este 18</h5>
      </a>
      <ul class="nav item">
        <% if user_signed_in? %>
          <li class="nav-item <%= 'active' if action_name == 'Salir'%>">
          <%= link_to "Salir", destroy_user_session_path, method: :delete, class:"btn btn-outline-primary" %>
          </li>
          <% else %>
          <li class="nav-item <%= 'active' if action_name == 'Iniciar sesión'%>">
          <%= link_to "Iniciar sesión", new_user_session_path, class:"btn btn-outline-primary" %>
          </li>
          <li class="nav-item <%= 'active' if action_name == 'Registrarse'%>">
          <%= link_to "Registro", new_user_registration_path, class:"btn btn-outline-primary" %>
          <% end %>
          </li>
        </ul>
    </nav>


    <%= yield %>
  </body>
</html>

app/views/shared/_notices.html.erb
<p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

 <% if user_signed_in? %>
 <div class="body mx-5">
 <% @todos.each_slice(3) do |todo| %>
   <div class="card-deck">
   <% todo.each do |todo| %>
   <%if todo.completed? %>
   <div class="card">
   <%= image_tag todo.task.photo, class: 'card-img-top img-thumbnail' %>
   <div class="card-body">
     <h5 class="card-title"><%= todo.task.name  %></h5>
     <%= link_to "Completado", update_todo_path(todo), method: :patch, class: "btn btn-outline-success" %>
     <%= link_to 'ver detalle', todo_path(todo), class: "btn btn-outline-info" %>
    </div>
    <div class="card-footer">
      <small class="text-muted"> <%= time_ago_in_words todo.updated_at %></small>
    </div>
    </div>
    <% else %>
 <div class="card">
   <%= image_tag todo.task.photo, class: 'card-img-top img-thumbnail' %>
   <div class="card-body">
     <h5 class="card-title"><%= todo.task.name  %></h5>
     <%= link_to "No Completado", update_todo_path(todo), method: :patch, class: "btn btn-outline-danger" %>
     <%= link_to 'ver detalle', todo_path(todo), class: "btn btn-outline-info" %>
    </div>
    <div class="card-footer">
      <small class="text-muted"> <%= time_ago_in_words todo.updated_at %></small>
    </div>
    </div>
    <% end %>
    <% end %>
 </div>
 <% end %>
 </div>

<%else%>


<% end %>

app/views/todos/index.html.erb
<h1>Todos#index</h1>
<% @todos.each do |todo| %>

       <%= todo.completed %>
        <%= todo.task.name %>
        <%= todo.user.email %>

    <% end %>

app/views/todos/show.html.erb
<h2>Todos#show</h2>

<p>
  <strong>Task:</strong>
  <%= @task.name %>
</p>
<p>
  <strong>Task:</strong>
  <%= @task.detail %>
</p>


<%= link_to 'Back', root_path %>